export const data = [
  {
    backdrop_path: '/ovt5KdS1oNwXkFPsgymhMoKvxKa.jpg',
    id: 929204,
    title: 'Wallace & Gromit: Vengeance Most Fowl',
    original_title: 'Wallace & Gromit: Vengeance Most Fowl',
    overview:
      'Gromit’s concern that Wallace is becoming too dependent on his inventions proves justified, when Wallace invents a “smart” gnome that seems to develop a mind of its own. When it emerges that a vengeful figure from the past might be masterminding things, it falls to Gromit to battle sinister forces and save his master… or Wallace may never be able to invent again!',
    poster_path: '/6BxK38ehxuX2dJmZIMpJcVNbYks.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [16, 35, 10751, 12],
    popularity: 448.485,
    release_date: '2024-12-18',
    video: false,
    vote_average: 7.721,
    vote_count: 253,
  },
  {
    backdrop_path: '/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg',
    id: 1241982,
    title: 'Moana 2',
    original_title: 'Moana 2',
    overview:
      "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    poster_path: '/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [16, 12, 10751, 35],
    popularity: 1666.532,
    release_date: '2024-11-21',
    video: false,
    vote_average: 6.997,
    vote_count: 867,
  },
  {
    backdrop_path: '/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg',
    id: 839033,
    title: 'The Lord of the Rings: The War of the Rohirrim',
    original_title: 'The Lord of the Rings: The War of the Rohirrim',
    overview:
      'A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.',
    poster_path: '/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [16, 14, 28, 12],
    popularity: 1000.057,
    release_date: '2024-12-05',
    video: false,
    vote_average: 6.5,
    vote_count: 334,
  },
  {
    backdrop_path: '/pAJX9KA8fL0ktVVVKNI5GyVfcWZ.jpg',
    id: 1355755,
    title: 'An Almost Christmas Story',
    original_title: 'An Almost Christmas Story',
    overview:
      'A young owl meets a lost little girl in New York City. Together, they try to get home for Christmas.',
    poster_path: '/mQC3nIJ9DQ74t9vFzUjqP8eohgX.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [16, 12, 14, 10751],
    popularity: 114.695,
    release_date: '2024-10-14',
    video: false,
    vote_average: 7.3,
    vote_count: 51,
  },
  {
    backdrop_path: '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
    id: 823219,
    title: 'Flow',
    original_title: 'Straume',
    overview:
      'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
    poster_path: '/imKSymKBK7o73sajciEmndJoVkR.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'lv',
    genre_ids: [16, 14, 12],
    popularity: 698.225,
    release_date: '2024-08-29',
    video: false,
    vote_average: 8.4,
    vote_count: 808,
  },
  {
    backdrop_path: '/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg',
    id: 762509,
    title: 'Mufasa: The Lion King',
    original_title: 'Mufasa: The Lion King',
    overview:
      'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
    poster_path: '/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [12, 10751, 16],
    popularity: 2784.981,
    release_date: '2024-12-18',
    video: false,
    vote_average: 7.388,
    vote_count: 755,
  },
  {
    backdrop_path: '/fzjH7kt1017R9EckLDmWmH5pGhD.jpg',
    id: 970450,
    title: 'Werewolves',
    original_title: 'Werewolves',
    overview:
      'A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.',
    poster_path: '/cRTctVlwvMdXVsaYbX5qfkittDP.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [28, 27, 53],
    popularity: 1075.085,
    release_date: '2024-12-04',
    video: false,
    vote_average: 6.5,
    vote_count: 201,
  },
  {
    backdrop_path: '/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
    id: 558449,
    title: 'Gladiator II',
    original_title: 'Gladiator II',
    overview:
      'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.',
    poster_path: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [28, 12, 18],
    popularity: 1733.875,
    release_date: '2024-11-05',
    video: false,
    vote_average: 6.7,
    vote_count: 2390,
  },
  {
    backdrop_path: '/uWOJbarUXfVf6B4o0368dh138eR.jpg',
    id: 426063,
    title: 'Nosferatu',
    original_title: 'Nosferatu',
    overview:
      'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
    poster_path: '/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [18, 14, 27],
    popularity: 515.703,
    release_date: '2024-12-25',
    video: false,
    vote_average: 6.693,
    vote_count: 1091,
  },
  {
    backdrop_path: '/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg',
    id: 845781,
    title: 'Red One',
    original_title: 'Red One',
    overview:
      "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
    poster_path: '/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [28, 14, 35],
    popularity: 1053.863,
    release_date: '2024-10-31',
    video: false,
    vote_average: 7.1,
    vote_count: 2077,
  },
  {
    backdrop_path: '/gKDFHQsEdnwZW0RC0htr0aYYH5W.jpg',
    id: 1154223,
    title: 'Hunting With Tigers',
    original_title: 'Tigres et Hyènes',
    overview:
      "Malik, a young Parisian hustler, discovers that his stepfather Serge, a famous bank robber, has been arrested along with his accomplices. During the trial, Iris, one of the accused's lawyers, Chérif, requests Malik to accept a dangerous heist in exchange for Serge and her client's liberty. Malik must convince and reunite Chérif's former partners to accomplish this high-risk stickup.",
    poster_path: '/lw6ovFjd6fhq6SEklcxP5axlVJn.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'fr',
    genre_ids: [28, 53],
    popularity: 107.832,
    release_date: '2024-11-22',
    video: false,
    vote_average: 6.1,
    vote_count: 59,
  },
  {
    backdrop_path: '/H39NvEXz23GE9iYQ4qqV4w1zWn.jpg',
    id: 728949,
    title: 'Nightbitch',
    original_title: 'Nightbitch',
    overview:
      'A woman, thrown into the stay-at-home routine of raising a toddler in the suburbs, slowly embraces the feral power deeply rooted in motherhood, as she becomes increasingly aware of the bizarre and undeniable signs that she may be turning into a dog.',
    poster_path: '/h49Pie8gM2jK0UHGFRjfPB3YTd.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [35, 27],
    popularity: 326.832,
    release_date: '2024-12-06',
    video: false,
    vote_average: 6.279,
    vote_count: 86,
  },
  {
    backdrop_path: '/d8x5rteAHXPCz71F3Q952bfeApH.jpg',
    id: 971606,
    title: 'Out of My Mind',
    original_title: 'Out of My Mind',
    overview:
      "Melody Brooks, a sixth grader with cerebral palsy, has a quick wit and a sharp mind, but because she is non-verbal and uses a wheelchair, she is not given the same opportunities as her classmates. When a young educator notices her student's untapped potential and Melody starts to participate in mainstream education, Melody shows that what she has to say is more important than how she says it.",
    poster_path: '/1JJKy0boc9G7papAlV9wwdXcrgO.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [18],
    popularity: 41.766,
    release_date: '2024-01-19',
    video: false,
    vote_average: 7.7,
    vote_count: 56,
  },
  {
    backdrop_path: '/9kgbf0PK8eooybcV3YhgBj0RXVh.jpg',
    id: 1319091,
    title: 'WWE Survivor Series: WarGames 2024',
    original_title: 'WWE Survivor Series: WarGames 2024',
    overview:
      'The 2024 Survivor Series: WarGames was a professional wrestling event produced by the American promotion WWE. It was the 38th annual Survivor Series, the third annual event specifically branded as "WarGames," and it took place on Saturday, November 30, 2024, at the Rogers Arena in Vancouver, British Columbia, Canada. The event aired via pay-per-view (PPV) and livestreaming and featured wrestlers from the promotion\'s Raw and SmackDown brand divisions. The event was based around the WarGames match, a team-based steel cage match where the roofless cage surrounded two rings placed side by side.',
    poster_path: '/6A1jDuqarD8pYFLmzWmAJZLtF7F.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [],
    popularity: 8.166,
    release_date: '2024-11-30',
    video: true,
    vote_average: 6.8,
    vote_count: 11,
  },
  {
    backdrop_path: '/hTmF6kuYQKyQ4EGfKsj9d5dmTu.jpg',
    id: 1038263,
    title: 'Maria',
    original_title: 'Maria',
    overview:
      "Maria Callas, the world's greatest opera singer, lives the last days of her life in 1970s Paris, as she confronts her identity and life.",
    poster_path: '/6xHKEYfrO1FpVZJJnKy5BhfWVCK.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [18, 10402],
    popularity: 78.834,
    release_date: '2024-11-27',
    video: false,
    vote_average: 6.9,
    vote_count: 146,
  },
  {
    backdrop_path: '/wYkrnn3eQY3vzMz4DJVMAgpQYYy.jpg',
    id: 1082195,
    title: 'The Order',
    original_title: 'The Order',
    overview:
      'A string of violent robberies in the Pacific Northwest leads a veteran FBI agent into a domestic terrorist plot to overthrow the federal government.',
    poster_path: '/1bJ2652AUnuK1WhlR0GLbJKVqMF.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [80, 18, 53],
    popularity: 48.528,
    release_date: '2024-12-05',
    video: false,
    vote_average: 6.7,
    vote_count: 124,
  },
  {
    backdrop_path: '/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg',
    id: 939243,
    title: 'Sonic the Hedgehog 3',
    original_title: 'Sonic the Hedgehog 3',
    overview:
      'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
    poster_path: '/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [28, 878, 35, 10751],
    popularity: 2943.593,
    release_date: '2024-12-19',
    video: false,
    vote_average: 7.563,
    vote_count: 662,
  },
  {
    backdrop_path: '/3WnoZw50qIfXsFnKr0LddEh5Jnf.jpg',
    id: 1222248,
    title: 'Number 24',
    original_title: 'Nr. 24',
    overview:
      "On the brink of the Second World War, a young Norwegian man's drive to resist the Nazis sets a new course for his future – and the future of his country.",
    poster_path: '/rzsmKSFEsEWBLbJ968abffnfYZ7.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'no',
    genre_ids: [10752, 36, 18],
    popularity: 1352.684,
    release_date: '2024-10-30',
    video: false,
    vote_average: 7.335,
    vote_count: 142,
  },
  {
    backdrop_path: '/jcEcle0wHoTpEkLmK4AcBKgWI45.jpg',
    id: 1100099,
    title: 'We Live in Time',
    original_title: 'We Live in Time',
    overview:
      'An up-and-coming chef and a recent divorcée find their lives forever changed when a chance encounter brings them together, in a decade-spanning, deeply moving romance.',
    poster_path: '/oeDNBgnlGF6rnyX1P1K8Vl2f3lW.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [10749, 18],
    popularity: 233.992,
    release_date: '2024-10-10',
    video: false,
    vote_average: 7.5,
    vote_count: 478,
  },
  {
    backdrop_path: '/rDa3SfEijeRNCWtHQZCwfbGxYvR.jpg',
    id: 539972,
    title: 'Kraven the Hunter',
    original_title: 'Kraven the Hunter',
    overview:
      "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
    poster_path: '/i47IUSsN126K11JUzqQIOi1Mg1M.jpg',
    media_type: 'movie',
    adult: false,
    original_language: 'en',
    genre_ids: [28, 12, 53],
    popularity: 3297.244,
    release_date: '2024-12-11',
    video: false,
    vote_average: 6.381,
    vote_count: 560,
  },
];
